alan-turing-institute/sqlsynthgen

.gitignore, .pylintrc, sqlsynthgen/create.py, sqlsynthgen/main.py, sqlsynthgen/make.py, sqlsynthgen/settings.py, tests/test_create.py, tests/test_main.py, tests/test_make.py, tests/test_settings.py, tests/utils.py
Finish off the CLI commands, plus a little bit of refactoring.
=> Implement create-tables command.

sqlsynthgen/create.py, sqlsynthgen/main.py, tests/test_create.py, tests/test_main.py
Add a new argument for adding many rows in one go. Also add a check that creates a new schema if necessary, when creating tables.
=> Insert multiple rows

sqlsynthgen/create.py, sqlsynthgen/main.py, sqlsynthgen/make.py, tests/examples/expected_ssg.py, tests/test_create.py
Closes #42 
- Converts the `num_rows_per_pass: 2` entry in the config .yaml into a `num_rows_per_pass = 2` member variable in the generator class when we do `make-generators ...`.
- Runs the generator that many times when we do `create-data ...`.
=> 42 num rows per pass

docs/source/index.rst, sqlsynthgen/main.py, tests/examples/src.dump, tests/test_main.py
1. Add a table without a PK to the test database via `src.dump` file
2. Add note to docs about tables without PKs
As far as I can tell, the basic functionality of SSG does work when a tables doesn't have a PK. However, vocabularies don't work (a relatively easy naming fix if we wanted).
=> 46 tables without pks

tests/test_base.py, tests/test_functional.py, tests/test_make.py, tests/test_providers.py, tests/test_utils.py, tests/utils.py
A slight improvement over the previous system since we now save the starting directory in `setUp` and return to it in `tearDown`. Previously, we did `chdir('../..')` in `tearDown`, which could go wrong if something unexpected happened in `setUp` or if an extra `chdir()` was used in the test functions themselves.
Some improvements that could be added here or in a future PR
- Reduce duplication by moving the `examples/` and `workspace/` directories to the test utils module and making them `Final`.
- `run_psql()` presumes that it is being called from the repo root directory. This doesn't feel good as it then matters which order you do the `setUp` calls in. Is there a way we can remove this reliance on the current working directory to run the db setup scripts with psql?
=> Change directory more safely in unit tests

.pylintrc, docs/source/faq.rst, docs/source/index.rst, sqlsynthgen/create.py, sqlsynthgen/main.py, sqlsynthgen/make.py, sqlsynthgen/settings.py, sqlsynthgen/utils.py, tests/test_create.py, tests/test_functional.py, tests/test_make.py, tests/test_settings.py
We manually set the schema name in for the whole connection session using an explicit `SET SEARCH_PATH TO` statement.
This allows the user to have a different destination schema name than the source schema.
The disadvantage is that we cannot support multiple source schemas (not that we did previously, but this makes it harder), though postgres does allow you to set more than one schema on a search path with `SET SEARCH_PATH TO schema1, schema2;`.
Would appreciate some testing on a real database.
=> Allow users to specify the destination schema name

sqlsynthgen/create.py, sqlsynthgen/main.py, sqlsynthgen/make.py, tests/examples/expected_ssg.py, tests/test_create.py, tests/test_main.py
The zipping of `sorted_tables` and `sorted_generators` started to fail when there were non-trivial foreign-key relations between vocabulary tables, which made them no longer all be at the beginning of `sorted_tables`. This PR switches to using a dictionary that maps table names to generators.
=> Move form sorted_generators to generator_dict

docs/source/index.rst, docs/source/installation.rst, docs/source/quickstart.rst, poetry.lock, pyproject.toml, tests/test_rst.py
This PR aims to document the simplest possible workflow:
- make tables, make generators, create tables & create data
- No vocab
- No stats
- No config file
Even though it is good to keep a quickstart simple, I do think that we should add at least two more examples, to show the use of the stats and vocab functions. I think it should be fine to do that in separate PRs, though.
=> Add quickstart docs with simplest workflow

sqlsynthgen/create.py, sqlsynthgen/main.py, tests/test_create.py
Running `create-vocab` twice used to crash with because of the uniqueness constraint violation when inserting the same data again. This one makes it rather print out the error as a warning, but soldiering on with the other tables.
This builds on #68, and the diff is going to be nicer if that one is merged first.
=> Allow reloading the same vocabulary without crashing

pyproject.toml, sqlsynthgen/make.py, tests/test_make.py
With this PR, you can now set a top-level setting in `config.yaml` to say `use-smartnoise-sql: False`, and the queries will be run raw, without SNSQL to noise them.
I also threw in a couple of unrelated tiny changes because I'm lazy to make one line PRs.
Closes #75
=> Add option to not use SmartnoiseSQL

.github/workflows/publish.yml
We'll need to make a PyPI project and generate an API token before this actually works.
I have added a step to check that our GitHub tag version is the same as the version in the pyproject.toml but it's a bit ugly. I'm sure there's already a solution to this problem and it's probably better than what I've got here.
=> Add workflow to publish to PyPI

sqlsynthgen/base.py, sqlsynthgen/providers.py, tests/examples/example_config.yaml, tests/examples/src.dump, tests/test_functional.py, tests/test_providers.py
Before this, SSG failed. This was causing issues when using SSG on OMOP, where empty tables are common.
=> ColumnValueProvider returns None when extracting values from empty tables

sqlsynthgen/create.py, sqlsynthgen/main.py, sqlsynthgen/settings.py, sqlsynthgen/templates/ssg.py.j2, tests/examples/expected_ssg.py, tests/test_create.py, tests/test_main.py, tests/test_settings.py, tests/utils.py
The user who runs the make- commands and the user who runs the create- commands may be different people. Therefore, it makes sense to make the db connection parameters optional.
There may be a neater way to do this (e.g. it might be better to validate on first use rather than in the `make_xyz` functions in `main.py`) but I think the current method still works.
Would it be best to also explicitly check for the dst db params in the `create_` funcs in `main.py`? At the moment, we don't.
=> Make src & dst database params optionals

poetry.lock, pyproject.toml
PyPI packages cannot have `git+` dependencies.
=> Install sqlacodegen from PyPI so that we can publish to PyPI

docs/source/quickstart.rst, sqlsynthgen/main.py, sqlsynthgen/providers.py, sqlsynthgen/remove.py, tests/examples/example_orm.py, tests/examples/remove_ssg.py, tests/test_functional.py, tests/test_main.py, tests/test_make.py, tests/test_remove.py
Adds `remove-data`, `remove-vocab` and `remove-tables` commands, which should be almost the exact opposite of their `create-` counterparts.
Closes #85
=> Rm commands

pyproject.toml
I noticed that we don't have a `homepage` link from the [PyPi page](https://pypi.org/project/sqlsynthgen/). We may as well add some other details whilst we're at it.
=> Add URLs and more detail to pyproject.toml

pyproject.toml
At the moment, https://pypi.org/project/sqlsynthgen/ isn't showing the homepage or docs URLs for some reason (see, for contrast, the numpy page).
=> Try different homepage and docs URLs

docs/source/faq.rst, sqlsynthgen/make.py, tests/examples/example_config.yaml, tests/examples/expected_ssg.py, tests/examples/row_generators.py, tests/examples/story_generators.py, tests/test_make.py
Makes for much nicer generators and human readable `src-stats.yaml`. Heavily backwards incompatible though.
Also logs a warning if any query returns no results, which can easily happen with `dp-queries` when using `censor_dims`.
=> make-stats to return dictionaries

.readthedocs.yaml, CONTRIBUTING.md, docs/source/tutorials/airbnb.rst, docs/source/tutorials/loan_applications.rst, sqlsynthgen/base.py, sqlsynthgen/main.py, tests/examples/loans/config1.yaml, tests/examples/loans/config2.yaml, tests/examples/loans/config3.yaml, tests/examples/loans/my_row_generators.py, tests/test_rst.py
Finishes the loans dataset tutorial.
I have not used story generators but have covered the other features (including the fact that we now have a SNS workaround for MariaDB).
Removes reference in readthedocs config to `docs/requirements.txt`, which no longer exists.
Uses `yaml.load()` rather than `yaml.safe_load()` as we are not using the safe dumper in `download_table()`. The alternative would be to use the safe version in both. The "unsafe" version gives us vocab export files that can look a bit like this, with the data type included when its literal value is not enough to fully define it:
```yaml
- A10: !!python/object/apply:decimal.Decimal
- '100'
A11: 12541
```
=> Finance tutorial

sqlsynthgen/main.py, sqlsynthgen/utils.py, tests/test_utils.py
At the moment, you need to manually validate the config but we should probably warn you whenever an invalid config is detected.
- Should we always warn or only if `--verbose` is requested?
- Is the error we print too verbose? If so, we could print only the first line of the message instead.
> WARNING:root:The config file is invalid:
{'a': 'b'} is not of type 'array'
_
Failed validating 'type' in schema['properties']['tables']['patternProperties']['.*']['properties']['row_generators']['items']['properties']['args']:
{'type': 'array'}
_
On instance['tables']['tkeys']['row_generators'][0]['args']:
{'a': 'b'}
=> Warn whenever an invalid config is loaded

sqlsynthgen/create.py, sqlsynthgen/make.py, sqlsynthgen/utils.py, tests/test_create.py, tests/test_main.py, tests/test_make.py
Changes
- Uses type hints and `MagicMock(spec=MockedClass)` feature to remove `# type: ignore` from tests. See https://stackoverflow.com/a/11283173/3324095
- Uses the abstract `Sequence` in place of `List` and `Mapping` in place of `Dict` in function parameters as this allows a wider range of types to be passed in. Keeps concrete types are still used for return types as they are more precise.
- Swaps `List` for `list` and `Dict` for `dict` as we require Python >= 3.9 and this feature was added in 3.9.
=> Sqla2 type hints iain

.github/workflows/pre-commit.yml, .github/workflows/tests.yml, .readthedocs.yaml, docs/source/installation.rst, pyproject.toml
- Bump the version number
- Remove the Cython workaround (not required as of the SQLAlchemy 2 upgrade)
=> 0.3.2 -> 0.3.3

.pylintrc, sqlsynthgen/base.py, sqlsynthgen/create.py, sqlsynthgen/main.py, sqlsynthgen/make.py, sqlsynthgen/remove.py, sqlsynthgen/templates/ssg.py.j2, sqlsynthgen/unique_generator.py, sqlsynthgen/utils.py, tests/examples/expected_ssg.py, tests/test_create.py, tests/test_functional.py, tests/test_main.py, tests/test_make.py, tests/test_utils.py
Change to using the `logging` module exclusively for text output, instead of `print` and `echo`. The new set up is such that there is `logger` object in `utils`, and all log prints should happen by calling one of its methods. Warning, error, and critical level messages will always go to stderr, info always to stdout, and debug to stdout only if `--verbose` was chosen.
Using this, I've also added a lot of debug-level print outs, so that the user can get feedback on e.g. which table is being uploaded or which generator run if they choose `--verbose`.
~This builds on #141, and thus the diff is messy. Once that one is merged, reset the base to `main` to clean up the diff.~
Did the reset.
=> Logging verbosity

docs/source/faq.rst
For a simple case (a table with a pk column and a varchar column), SSG works fine with SQL Server once you have installed the two extra dependencies (I'm not sure whether it's worth adding `pyodbc` to the Poetry requirements since you have to manually install the odbc drivers anyway).
There are SQL Server [images](https://hub.docker.com/_/microsoft-mssql-server), which we could use to add a functional test if we wanted.
=> Add instructions for SQL Server

sqlsynthgen/make.py, sqlsynthgen/providers.py, tests/examples/example_orm.py, tests/examples/expected_ssg.py, tests/examples/src.dump, tests/test_functional.py
- Check that we support unrecognised columns that have a size, such as `column_with_unusual_type_and_length bit(3)`
- Mark provider methods as `@staticmethod`s if they don't use `self`.
=> Static builtin providers

sqlsynthgen/make.py, sqlsynthgen/providers.py, tests/examples/example_orm.py, tests/examples/expected_ssg.py, tests/examples/src.dump, tests/test_functional.py, tests/test_remove.py
=> Default to null_provider for unrecognised column types, with warning
